create database transfers_test;

use transfers_test;

/* Creation of the account table */
CREATE TABLE  ACCOUNT (
	ID INT(20) NOT NULL AUTO_INCREMENT,
	NAME  VARCHAR(30),
	BALANCE  DOUBLE,
	PRIMARY KEY (ID)
);

/* Creation of the transfer table */
CREATE TABLE  TRANSFER (
	ID INT(20) NOT NULL AUTO_INCREMENT,
	SOURCE_ACCOUNT INT(20),
	DESTINATION_ACCOUNT INT(20),
	AMOUNT DOUBLE,
	CONSTRAINT FK_SOURCE_ACCOUNT FOREIGN KEY (SOURCE_ACCOUNT) REFERENCES ACCOUNT (ID),
	CONSTRAINT FK_DESTINATION_ACCOUNT FOREIGN KEY (DESTINATION_ACCOUNT) REFERENCES ACCOUNT (ID),
	PRIMARY KEY (ID)
);

/* Run to have some accounts */
INSERT INTO ACCOUNT (NAME,BALANCE) VALUES ("one",150);
INSERT INTO ACCOUNT (NAME,BALANCE) VALUES ("two",300);
