---
server:
  port: 8080
  contextPath: /EPaymentApp
---
datasource:
  url: jdbc:mysql://localhost:3306/transfers_test
  username: root
  password: 123456
  driverClassName: com.mysql.jdbc.Driver
  defaultSchema:
  maxPoolSize: 20
  hibernate:
    hbm2ddl.method: update
    show_sql: false
    format_sql: false
    dialect: org.hibernate.dialect.MySQLDialect

