create database test_mifinity;

use test_mifinity;

/* creation of the role table */
CREATE TABLE  ROLE (
	ID INT(20) NOT NULL AUTO_INCREMENT,
	ROLE_NAME  VARCHAR(30),
	PRIMARY KEY (ID)
);

/* creation of the user table */
CREATE TABLE  USER (
	ID INT(20) NOT NULL AUTO_INCREMENT,
	USER_NAME VARCHAR(30),
	PASSWORD VARCHAR(30),
	ROLE_ID INT(30) NOT NULL,
	CONSTRAINT FK_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID),
	UNIQUE KEY UQ_USER_NAME (USER_NAME),
	PRIMARY KEY (ID)
);

/* creation of the credit card table */
CREATE TABLE CREDIT_CARD (
	ID INT(20) NOT NULL AUTO_INCREMENT,
	CARD_NUMBER VARCHAR(40),
	EXPIRY_DATE DATE,
	USER_ID INT(20) NOT NULL,
	CONSTRAINT FK_USER_ID FOREIGN KEY(USER_ID ) REFERENCES USER(ID),
	UNIQUE KEY UQ_CARD_NUMBER  (CARD_NUMBER ),
	PRIMARY KEY(ID)
);

/*Initialize tables*/
INSERT INTO ROLE (ID,ROLE_NAME) VALUES (1,"ADMIN");
INSERT INTO ROLE (ID,ROLE_NAME) VALUES (2,"USER");
INSERT INTO USER (ID,USER_NAME, PASSWORD,ROLE_ID) VALUES (1,"admin","admin",1);